### ISSUE TITLE
Embedding video tweets fails

### ISSUE THREAD

**Issue by aadilayub** [KevinBatdorf/wp-xeet#9]
Embedding [this tweet](https://twitter.com/StopEvictionKHI/status/1430036094008037379), which is quoting another tweet causes the block to get corrupted.

[Screencast from 2023-09-06 12-47-51.webm](https://github.com/KevinBatdorf/wp-xeet/assets/31581044/8a5fa234-1b8a-4346-a975-53195f6082db)

I'm using the latest successful build of the plugin.

**Comment by aadilayub** [comment]
I did some more testing and realizing it's the video part of the tweet that's causing the block to error out, not the quoting part.

e.g. trying to embed [this tweet](https://twitter.com/kentcdodds/status/1445103851783082002?s=20) fails

**Comment by KevinBatdorf** [comment]
Thanks for reporting. I see what's happening. I'll fix it tonight or tomorrow.

**Comment by KevinBatdorf** [comment]
This should be fixed now in #10 I was ill last weekend so apologies for the delay! 

If you have any other issues let me know. I don't have tests in place yet so something could break, but I tried loading other tweets and everything seemed ok.

**Comment by aadilayub** [comment]
Thanks so much and no worries about the delay! Works great on my end.
